// This file is automatically generated. Do not modify it manually.
'use client';
import { useState, useEffect, useMemo } from 'react';
import {
  doc,
  onSnapshot,
  getDoc,
  DocumentReference,
  DocumentData,
  DocumentSnapshot,
  FirestoreError,
} from 'firebase/firestore';
import { useFirestore } from '@/firebase/provider';
import { errorEmitter } from '@/firebase/error-emitter';
import { FirestorePermissionError } from '@/firebase/errors';

export function useDoc(ref: DocumentReference | null) {
  const [snapshot, setSnapshot] =
    useState<DocumentSnapshot<DocumentData> | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<FirestoreError | null>(null);

  useEffect(() => {
    if (!ref) {
      setLoading(false);
      setSnapshot(null);
      return;
    }
    setLoading(true);
    const unsubscribe = onSnapshot(
      ref,
      (snapshot) => {
        setSnapshot(snapshot);
        setLoading(false);
        setError(null);
      },
      (err) => {
        const permissionError = new FirestorePermissionError({
          path: ref.path,
          operation: 'get',
        });
        errorEmitter.emit('permission-error', permissionError);
        setError(err);
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, [ref]);

  return { snapshot, loading, error };
}

export function useDocData(ref: DocumentReference | null) {
  const { snapshot, loading, error } = useDoc(ref);
  const data = useMemo(() => {
    if (snapshot?.exists()) {
      return { id: snapshot.id, ...snapshot.data() };
    }
    return undefined;
  }, [snapshot]);
  return { data, loading, error };
}

export function useDocOnce(ref: DocumentReference | null) {
  const [snapshot, setSnapshot] =
    useState<DocumentSnapshot<DocumentData> | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<FirestoreError | null>(null);

  useEffect(() => {
    if (!ref) {
      setLoading(false);
      return;
    }
    getDoc(ref)
      .then((snapshot) => {
        setSnapshot(snapshot);
        setLoading(false);
      })
      .catch((err) => {
        const permissionError = new FirestorePermissionError({
          path: ref.path,
          operation: 'get',
        });
        errorEmitter.emit('permission-error', permissionError);
        setError(err);
        setLoading(false);
      });
  }, [ref]);

  return { snapshot, loading, error };
}
