// This file is automatically generated. Do not modify it manually.
'use client';
import { useState, useEffect, useMemo } from 'react';
import {
  onSnapshot,
  getDocs,
  Query,
  DocumentData,
  QuerySnapshot,
  FirestoreError,
} from 'firebase/firestore';
import { errorEmitter } from '@/firebase/error-emitter';
import { FirestorePermissionError } from '@/firebase/errors';

export function useCollection(q: Query | null) {
  const [snapshot, setSnapshot] = useState<QuerySnapshot<DocumentData> | null>(
    null
  );
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<FirestoreError | null>(null);

  useEffect(() => {
    if (!q) {
      setLoading(false);
      setSnapshot(null);
      return;
    }
    setLoading(true);
    const unsubscribe = onSnapshot(
      q,
      (snapshot) => {
        setSnapshot(snapshot);
        setLoading(false);
        setError(null);
      },
      (err) => {
        // Attempt to extract path for better error reporting
        // CollectionReference has .path, but Query does not.
        // We use internal segments as a fallback for debugging.
        let path = 'query';
        if ('path' in q) {
          path = (q as any).path;
        } else if ((q as any)._query?.path?.segments) {
          path = (q as any)._query.path.segments.join('/');
        }

        const permissionError = new FirestorePermissionError({
          path: path,
          operation: 'list',
        });
        errorEmitter.emit('permission-error', permissionError);
        setError(err);
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, [q]);

  return { snapshot, loading, error };
}

export function useCollectionData(q: Query | null) {
  const { snapshot, loading, error } = useCollection(q);
  const data = useMemo(
    () => snapshot?.docs.map((doc) => ({ id: doc.id, ...doc.data() })),
    [snapshot]
  );
  return { data, loading, error };
}

export function useCollectionOnce(q: Query | null) {
  const [snapshot, setSnapshot] =
    useState<QuerySnapshot<DocumentData> | null>(
      null
    );
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<FirestoreError | null>(null);

  useEffect(() => {
    if (!q) {
      setLoading(false);
      return;
    }
    getDocs(q)
      .then((snapshot) => {
        setSnapshot(snapshot);
        setLoading(false);
      })
      .catch((err) => {
        let path = 'query';
        if ('path' in q) {
          path = (q as any).path;
        } else if ((q as any)._query?.path?.segments) {
          path = (q as any)._query.path.segments.join('/');
        }
        const permissionError = new FirestorePermissionError({
          path: path,
          operation: 'list',
        });
        errorEmitter.emit('permission-error', permissionError);
        setError(err);
        setLoading(false);
      });
  }, [q]);

  return { snapshot, loading, error };
}
