// This file is automatically generated. Do not modify it manually.
'use client';
import React, {
  createContext,
  useContext,
  ReactNode,
  useState,
  useEffect,
} from 'react';
import { initializeFirebase, FirebaseServices } from '@/firebase';
import { FirebaseProvider } from '@/firebase/provider';

const FirebaseClientContext = createContext<FirebaseServices | null>(null);

export function useFirebaseClient(): FirebaseServices {
  const context = useContext(FirebaseClientContext);
  if (context === null) {
    throw new Error(
      'useFirebaseClient must be used within a FirebaseClientProvider'
    );
  }
  return context;
}

export function FirebaseClientProvider({ children }: { children: ReactNode }) {
  const [firebase, setFirebase] = useState<FirebaseServices | null>(null);

  useEffect(() => {
    const firebaseServices = initializeFirebase();
    setFirebase(firebaseServices);
  }, []);

  if (!firebase) {
    // You can render a loading spinner or some placeholder here.
    return null;
  }

  return (
    <FirebaseClientContext.Provider value={firebase}>
      <FirebaseProvider {...firebase}>{children}</FirebaseProvider>
    </FirebaseClientContext.Provider>
  );
}
