// This file is automatically generated. Do not modify it manually.
// Your Firebase project's configuration
export const firebaseConfig = {
  projectId: "studio-9506215785-8115c",
  appId: "1:594984144458:web:46d77b2944c2d928a7a0b3",
  apiKey: "AIzaSyCby8FDcZnHGHKSkCnqG5xfkuHWQR-Yt4s",
  authDomain: "studio-9506215785-8115c.firebaseapp.com",
  storageBucket: "studio-9506215785-8115c.appspot.com",
  messagingSenderId: "594984144458",
  measurementId: "",
};
