// This file is automatically generated. Do not modify it manually.
import { User } from 'firebase/auth';

export type SecurityRuleContext = {
  path: string;
  operation: 'get' | 'list' | 'create' | 'update' | 'delete';
  requestResourceData?: any;
};

export class FirestorePermissionError extends Error {
  context: SecurityRuleContext;
  fullMessage: string;

  constructor(context: SecurityRuleContext) {
    const message = `Firestore Permission Denied: Cannot ${context.operation} at ${context.path}`;
    super(message);
    this.name = 'FirestorePermissionError';
    this.context = context;
    this.fullMessage = message;
    Object.setPrototypeOf(this, FirestorePermissionError.prototype);
  }

  toString(): string {
    return this.fullMessage;
  }

  toDebugString(user: User | null): string {
    const request = {
      auth: user
        ? {
            uid: user.uid,
            token: {
              email: user.email,
              email_verified: user.emailVerified,
              phone_number: user.phoneNumber,
              name: user.displayName,
              picture: user.photoURL,
              firebase: {
                // This part is a simplification. Real token has more details.
                identities: user.providerData.reduce(
                  (acc, p) => ({ ...acc, [p.providerId]: [p.uid] }),
                  {}
                ),
                sign_in_provider: user.providerData[0]?.providerId || 'custom',
              },
            },
          }
        : null,
      method: this.context.operation,
      path: `/databases/(default)/documents/${this.context.path}`,
      ...(this.context.requestResourceData && {
        resource: {
          data: this.context.requestResourceData,
        },
      }),
    };

    return `The following request was denied by Firestore Security Rules:\n${JSON.stringify(
      request,
      null,
      2
    )}`;
  }
}
