// This file is automatically generated. Do not modify it manually.
type EventMap = Record<string, any>;
type EventKey<T extends EventMap> = string & keyof T;
type EventReceiver<T> = (params: T) => void;

interface Emitter<T extends EventMap> {
  on<K extends EventKey<T>>(eventName: K, fn: EventReceiver<T[K]>): void;
  off<K extends EventKey<T>>(eventName: K, fn: EventReceiver<T[K]>): void;
  emit<K extends EventKey<T>>(eventName: K, params: T[K]): void;
}

export function createNanoEvents<T extends EventMap>(): Emitter<T> {
  let events: { [K in EventKey<T>]?: EventReceiver<T[K]>[] } = {};

  return {
    on(eventName, fn) {
      events[eventName] = events[eventName] || [];
      events[eventName]?.push(fn);
    },
    off(eventName, fn) {
      if (events[eventName]) {
        events[eventName] = events[eventName]?.filter((cb) => cb !== fn);
      }
    },
    emit(eventName, params) {
      events[eventName]?.forEach((fn) => fn(params));
    },
  };
}

import { FirestorePermissionError } from './errors';

interface ErrorEvents {
  'permission-error': FirestorePermissionError;
}

export const errorEmitter = createNanoEvents<ErrorEvents>();
