// This file is automatically generated. Do not modify it manually.
import { initializeApp, getApp, getApps, FirebaseApp } from 'firebase/app';
import { getAuth, Auth } from 'firebase/auth';
import { getFirestore, Firestore } from 'firebase/firestore';
import { firebaseConfig } from '@/firebase/config';
import {
  useCollection,
  useCollectionData,
  useCollectionOnce,
} from './firestore/use-collection';
import { useDoc, useDocOnce, useDocData } from './firestore/use-doc';
import { useUser } from './auth/use-user';
import {
  FirebaseProvider,
  useFirebase,
  useFirebaseApp,
  useAuth,
  useFirestore,
} from './provider';
import { FirebaseClientProvider } from './client-provider';
import { useMemo } from 'react';

export interface FirebaseServices {
  app: FirebaseApp;
  auth: Auth;
  firestore: Firestore;
}

let firebaseInstance: FirebaseServices | null = null;

export function initializeFirebase(): FirebaseServices {
  if (firebaseInstance) {
    return firebaseInstance;
  }

  const app =
    getApps().length === 0 ? initializeApp(firebaseConfig) : getApp();
  const auth = getAuth(app);
  const firestore = getFirestore(app);

  firebaseInstance = { app, auth, firestore };
  return firebaseInstance;
}

/**
 * A specialized hook to stabilize Firebase references or queries.
 * Use this to wrap document references or collection queries that depend on other state.
 * @param factory A function that returns a Firebase reference or query.
 * @param deps The dependencies of the reference/query.
 * @returns A stable reference or query.
 */
export function useMemoFirebase<T>(factory: () => T, deps: React.DependencyList): T {
  return useMemo(factory, deps);
}

export {
  FirebaseProvider,
  FirebaseClientProvider,
  useFirebase,
  useFirebaseApp,
  useAuth,
  useFirestore,
  useUser,
  useCollection,
  useCollectionData,
  useCollectionOnce,
  useDoc,
  useDocData,
  useDocOnce,
};
