// This file is automatically generated. Do not modify it manually.
'use client';

import { useEffect } from 'react';
import { errorEmitter } from '@/firebase/error-emitter';
import { FirestorePermissionError } from '@/firebase/errors';
import { useUser } from '@/firebase/auth/use-user';
import { useToast } from '@/hooks/use-toast';

export function FirebaseErrorListener() {
  const { user } = useUser();
  const { toast } = useToast();

  useEffect(() => {
    const handlePermissionError = (error: FirestorePermissionError) => {
      console.error('Firestore Permission Error:', error.toString());
      if (process.env.NODE_ENV === 'development') {
        const detailedError = error.toDebugString(user);
        toast({
          variant: 'destructive',
          title: 'Firestore Permission Denied',
          description: detailedError,
          duration: 10000,
        });
        // Throwing the error will activate the Next.js error overlay
        throw new Error(detailedError);
      } else {
        toast({
          variant: 'destructive',
          title: 'Error',
          description: 'You do not have permission to perform this action.',
        });
      }
    };

    errorEmitter.on('permission-error', handlePermissionError);

    return () => {
      errorEmitter.off('permission-error', handlePermissionError);
    };
  }, [user, toast]);

  return null; // This component does not render anything
}
